project:
  type: website
  output-dir: docs
website:
  title: "Jay Lowe's Blog"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/jay-lowe-a21075163/
      - icon: twitter
        text: Twitter
        href: https://twitter.com/ogjaylowe
      - icon: github
        text: Github
        href: https://github.com/ogjaylowe
  favicon: logo.png
  site-url: https://ogjaylowe.com
format:
  html:
    theme: materia
    css: styles.css
    include-after-body: ./footer.html


